// Creates a new deck project from this template.
// Usage: node scripts/new-deck.js <destination-directory>
// Copies only what a deck needs, and gives the deck its own storageKey so that
// editor state saved in the browser never mixes between decks.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const INCLUDE = [
  'scripts', 'html', 'assets', 'templates', 'docs',
  'deck.config.json', 'package.json', '.gitignore',
  'CUSTOMIZE.md', 'CUSTOMIZE.ko.md',
  'LICENSE', 'LICENSE-CONTENT.md', 'THIRD-PARTY-NOTICES.md',
];
// Build output is regenerated by the new deck's own build.
const SKIP = new Set([path.join('html', 'deck.html')]);

function slug(name) {
  const s = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return s || 'deck';
}

function assertEmptyDestination(dest) {
  if (!fs.existsSync(dest)) return;
  if (!fs.statSync(dest).isDirectory()) throw new Error(`destination is a file: ${dest}`);
  if (fs.readdirSync(dest).length) throw new Error(`destination is not empty: ${dest}`);
}

function copyTemplate(dest) {
  for (const name of INCLUDE) {
    const from = path.join(ROOT, name);
    if (!fs.existsSync(from)) continue;
    fs.cpSync(from, path.join(dest, name), {
      recursive: true,
      filter: src => !SKIP.has(path.relative(ROOT, src)),
    });
  }
}

function personalize(dest) {
  const file = path.join(dest, 'deck.config.json');
  const config = JSON.parse(fs.readFileSync(file, 'utf8'));
  config.storageKey = `${slug(path.basename(dest))}-v1`;
  fs.writeFileSync(file, JSON.stringify(config, null, 2) + '\n');
  return config.storageKey;
}

function main() {
  const arg = process.argv[2];
  if (!arg) {
    console.error('usage: node scripts/new-deck.js <destination-directory>');
    process.exit(2);
  }
  const dest = path.resolve(arg);
  if (dest === ROOT || dest.startsWith(ROOT + path.sep)) {
    throw new Error('destination must be outside the template folder');
  }
  assertEmptyDestination(dest);
  fs.mkdirSync(dest, { recursive: true });
  copyTemplate(dest);
  const storageKey = personalize(dest);
  console.log(JSON.stringify({
    deck: dest,
    storageKey,
    config: path.join(dest, 'deck.config.json'),
    build: `node ${path.join(dest, 'scripts', 'build-deck.js')}`,
    output: path.join(dest, 'html', 'deck.html'),
  }, null, 2));
}

if (require.main === module) {
  try { main(); } catch (err) { console.error(err.message); process.exit(1); }
}

module.exports = { slug };
